[package]
name = "bevy_overture_maps"
version = "0.4.0"
edition = "2024"

[profile.release]
codegen-units = 1

[workspace]
resolver = "2"
members = ["app", "cli"]

[workspace.dependencies]
arrow = { version = "58.1.0", features = [
    "ipc",
    "test_utils",
    "prettyprint",
    "json",
] }
bevy = { version = "0.18.1", features = ["jpeg",     "bevy_camera_controller",
"free_camera",
"bevy_core_pipeline"] }
bevy_asset = "0.18.1"
bevy_mesh = "0.18.1"
duckdb = { version = "1.10502.0", features = ["bundled"] }
geo = { version = "0.33.1", features = [] }
geozero = { version = "0.15.1", features = ["with-wkb"] }
geo-types = { version = "0.7.11" }
parquet = "58.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.28" }

[dependencies]
arrow = { workspace = true }
bevy = { workspace = true }
bevy_asset = { workspace = true }
bevy_mesh = { workspace = true }
duckdb = { workspace = true }
geo = { workspace = true }
geozero = { workspace = true }
geo-types = { workspace = true }
parquet = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = "0.28"
strum_macros = "0.28"
